"""Business rules extracted from BRS (CAM).
Each constant links back to its Requirement ID and source page.
Generated by BRS to QA Automation Platform — review before running.
"""
from decimal import Decimal

# REQ-CAM-RULE3-001 | Source: CAM-BRS-demo.txt หน้า NOT_FOUND / 2. Rule 3 ธุรกรรมมูลค่าสูง
# BRS: - ระบบต้องแสดงรายการลูกค้าที่มียอดรวมธุรกรรมมากกว่าหรือเท่ากับ 200,000 บาท ย้อนหลัง 14 วัน ในรายงาน High Value Alert
REQ_CAM_RULE3_001_THRESHOLD = Decimal("200000")  # unit: บาท


def meets_req_cam_rule3_001(value: Decimal) -> bool:
    """Return True when value satisfies '>= 200000' (REQ-CAM-RULE3-001)."""
    return value >= REQ_CAM_RULE3_001_THRESHOLD


# REQ-CAM-RULE5-002 | Source: CAM-BRS-demo.txt หน้า NOT_FOUND / 4. Rule 5 Validation หน้าจอค้นหาลูกค้า
# BRS: - เจ้าหน้าที่Compliance ต้องกรอกหมายเหตุได้ความยาวไม่เกิน 200 ตัวอักษร และระบบต้องแสดงข้อความ "หมายเหตุยาวเกินกำหนด" เมื่อเกิน หากค่าว่างให้บันทึกได้
REQ_CAM_RULE5_002_THRESHOLD = Decimal("200")  # unit: ตัวอักษร


def meets_req_cam_rule5_002(value: Decimal) -> bool:
    """Return True when value satisfies '<= 200' (REQ-CAM-RULE5-002)."""
    return value <= REQ_CAM_RULE5_002_THRESHOLD

