"""Test Case catalog of the WebQA2026 website (source of WEBQA2026_TEST_CASES.xlsx / .csv).
Each automated case = one Playwright test with the same ID in frontend/e2e/website/*.spec.ts.
Fields: id: (priority, type, precondition, steps ["a", "b"], expected, test data)"""

MODULES = {
    "AUTH": ("Login / บัญชีผู้ใช้", "01-auth.spec.ts"), "NAV": ("เมนูตามสิทธิ์ (UI)", "02-navigation-rbac.spec.ts"),
    "RBAC": ("สิทธิ์ฝั่ง Backend", "02-navigation-rbac.spec.ts"), "PRJ": ("Projects", "03-projects-documents.spec.ts"),
    "DOC": ("เอกสาร BRS", "03-projects-documents.spec.ts"), "REQ": ("Requirement Explorer", "04-requirements.spec.ts"),
    "CLR": ("Clarification & Conflict", "04-requirements.spec.ts"), "DASH": ("Dashboard", "04-requirements.spec.ts"),
    "TRC": ("Traceability", "04-requirements.spec.ts"), "TD": ("Test Scenario / Test Case", "05-test-design-automation.spec.ts"),
    "AUTO": ("Automation Generator", "05-test-design-automation.spec.ts"), "RUN": ("Test Runs", "05-test-design-automation.spec.ts"),
    "WEX": ("Web Explorer", "06-web-explorer.spec.ts"), "REC": ("Web Recorder", "07-web-recorder.spec.ts"),
    "HIS": ("Web History + Detail", "08-web-history.spec.ts"), "LIB": ("คลัง Test Case รวม", "08-web-history.spec.ts"),
    "ADM": ("Settings / Users", "09-admin.spec.ts"), "AUD": ("Audit Log", "09-admin.spec.ts"),
    "API": ("API Contract", "10-api-security.spec.ts"), "SEC": ("Security", "10-api-security.spec.ts"),
    "PERF": ("Performance", "perf/webqa_perf.py"), "MAN": ("Manual / Exploratory", "-"),
}

ADMIN = "Login เป็น admin"
CASES = {
 # ---------------------------------------------------------------- AUTH
 "WQA-AUTH-01": ("High", "Functional", "มีบัญชี admin ที่เปลี่ยนรหัสผ่านแล้ว", ["เปิด /login", "กรอก Username/Password ที่ถูกต้อง", "กด เข้าสู่ระบบ"], "ไปหน้า /projects แสดงหัวข้อ Projects และชื่อ System Admin ที่แถบบน", "admin / Website-E2e!Pass1"),
 "WQA-AUTH-02": ("High", "Negative", "-", ["เปิด /login", "กรอก admin + รหัสผิด", "กด เข้าสู่ระบบ"], "แสดง 'Username หรือ Password ไม่ถูกต้อง' และยังอยู่หน้า Login", "Wrong-Pass-123!"),
 "WQA-AUTH-03": ("High", "Security", "-", ["Login ด้วย user ที่ไม่มีในระบบ"], "ข้อความเหมือนรหัสผิดทุกตัวอักษร (ไม่เปิดเผยว่ามี user หรือไม่)", "no_such_user_e2e"),
 "WQA-AUTH-04": ("Medium", "Negative", "-", ["เปิด /login", "กด เข้าสู่ระบบ โดยไม่กรอก"], "แสดง 'กรุณากรอก Username' และ 'กรุณากรอก Password' และไม่มีการเรียก /api/auth/login", "-"),
 "WQA-AUTH-05": ("Low", "Security", "-", ["เปิด /login", "ตรวจช่อง Password"], "ช่อง Password เป็น type=password (ตัวอักษรถูกปิดบัง)", "-"),
 "WQA-AUTH-06": ("High", "Functional", "Admin สร้างผู้ใช้ใหม่ (รหัสชั่วคราว)", ["Login ด้วยรหัสชั่วคราว → ถูกพาไป /change-password", "ลองรหัส < 10 ตัว / ไม่มีตัวใหญ่ / ยืนยันไม่ตรง / ซ้ำรหัสเดิม", "ใส่รหัสใหม่ที่ถูกกฎ", "ออกจากระบบแล้ว Login ด้วยรหัสเดิมและรหัสใหม่"], "แต่ละกรณีแสดงข้อความกฎรหัสผ่านที่ถูกต้อง · เปลี่ยนสำเร็จไป /projects · รหัสเดิมใช้ไม่ได้ รหัสใหม่ใช้ได้", "Temp-Pass!12345 → New-Strong!Pass1"),
 "WQA-AUTH-07": ("Medium", "Negative", "ผู้ใช้ใหม่ต้องเปลี่ยนรหัสผ่าน", ["ใส่รหัสผ่านปัจจุบันผิด แต่รหัสใหม่ถูกกฎ", "กด บันทึก"], "Server ปฏิเสธ แสดงกล่อง error และยังอยู่หน้าเปลี่ยนรหัสผ่าน", "Not-The-Current!1"),
 "WQA-AUTH-08": ("High", "Functional", ADMIN, ["กด ออกจากระบบ", "พิมพ์ URL /projects"], "กลับหน้า Login และเปิดหน้าภายในไม่ได้จนกว่าจะ Login ใหม่", "-"),
 "WQA-AUTH-09": ("Medium", "Functional", "ยังไม่ Login", ["เปิดลิงก์ /web-explorer/history ตรง ๆ", "Login"], "หลัง Login กลับไปหน้า Web History (หน้าที่ตั้งใจเปิด)", "-"),
 "WQA-AUTH-10": ("Medium", "Security", ADMIN, ["เปิดแท็บ/หน้าต่างใหม่ (context ใหม่)", "เปิด /projects"], "ต้อง Login ใหม่ (Session เก็บใน sessionStorage ต่อแท็บ)", "-"),
 # ---------------------------------------------------------------- NAV / RBAC
 "WQA-NAV-01": ("High", "RBAC", ADMIN, ["เปิด Projects → CAM", "ตรวจเมนูด้านซ้าย"], "เห็นทุกกลุ่มเมนู รวม Upload, Generator ทุกชนิด, GitHub, Settings, Audit Log และปุ่ม Create Project", "-"),
 "WQA-NAV-02": ("High", "RBAC", "Login เป็น ba", ["เปิด Projects → CAM", "ตรวจเมนู"], "ไม่มี Upload / Postman / Playwright / JMeter / GitHub / Settings / Audit Log / Create Project แต่มี Requirement Explorer", "-"),
 "WQA-NAV-03": ("High", "RBAC", "Login เป็น qa_manual", ["เปิด CAM", "ตรวจเมนู"], "มี Upload และ Pytest แต่ไม่มี Postman / SQL / Playwright / JMeter / GitHub / Settings", "-"),
 "WQA-NAV-04": ("High", "RBAC", "Login เป็น qa_auto", ["เปิด CAM", "ตรวจเมนู"], "มี Postman / Playwright / JMeter / GitHub / Test Runs แต่ไม่มี Upload", "-"),
 "WQA-NAV-05": ("High", "Security", "Login เป็น ba", ["พิมพ์ URL หน้า Upload ของ CAM ตรง ๆ"], "แสดง 'ไม่มีสิทธิ์' และไม่แสดงช่องอัปโหลด", "-"),
 "WQA-NAV-06": ("Low", "Functional", ADMIN, ["เลือก Project CAM จากแถบบน", "กด Breadcrumb 'Projects'"], "ไปหน้าของ Project แล้วกลับหน้ารายการ Projects ได้", "-"),
 "WQA-RBAC-01": ("Critical", "Security", "Token ของ ba", ["เรียก API: สร้าง Project, Paste Text, เริ่ม Recorder, Audit Log, Users"], "ทุกคำขอได้ 403", "-"),
 "WQA-RBAC-02": ("High", "Security", "Token ของ qa_manual", ["GET /web-history", "POST /web-explorer/{id}/run"], "อ่านได้ 200 แต่รันได้ 403", "-"),
 "WQA-RBAC-03": ("Medium", "RBAC", "Token ทุก Role", ["GET /auth/me"], "ได้รายการสิทธิ์ · มีสิทธิ์ settings เฉพาะ Admin", "-"),
 # ---------------------------------------------------------------- PRJ / DOC
 "WQA-PRJ-01": ("Medium", "Functional", ADMIN, ["เปิด /projects"], "แถว CAM แสดงชื่อ Project และ Requirements = 9", "Seed demo"),
 "WQA-PRJ-02": ("Medium", "Negative", ADMIN, ["กด Create Project", "Code = 1ab, เว้นชื่อ", "กด สร้าง", "กด ยกเลิก"], "แจ้ง 'ตัวพิมพ์ใหญ่/ตัวเลข 2–16 ตัว เริ่มด้วยตัวอักษร' และ 'กรุณากรอกชื่อ Project' · ยกเลิกแล้ว dialog ปิด", "1ab"),
 "WQA-PRJ-03": ("High", "Functional", ADMIN, ["Create Project ด้วย Code ตัวเล็ก + ชื่อ + คำอธิบาย", "กด สร้าง"], "แจ้ง 'สร้าง Project แล้ว' และ Code ตัวใหญ่ขึ้นในรายการ", "e2exxxxx"),
 "WQA-PRJ-04": ("Medium", "Negative", "มี Project จาก PRJ-03", ["Create Project ด้วย Code ซ้ำ"], "Dialog ยังเปิดพร้อม error และมี Project code นั้นเพียง 1 รายการ", "Code ซ้ำ"),
 "WQA-PRJ-05": ("Low", "Functional", "Project จาก PRJ-03", ["เปิด Project Detail", "กดแท็บ Members"], "มีแท็บ Documents & Versions / Members / Module Codes และ Members มี admin", "-"),
 "WQA-DOC-01": ("Critical", "Functional", "Project ใหม่", ["Upload → เลือก CAM_BRS_v1.txt", "เปิด Processing"], "แถวผลลัพธ์ 'สำเร็จ' พร้อม SHA-256 · Processing = READY_FOR_REVIEW", "samples/CAM_BRS_v1.txt"),
 "WQA-DOC-02": ("High", "Negative", "Project ใหม่", ["เลือก sample.docx และ bad.pdf พร้อมกัน"], "docx = สำเร็จ, bad.pdf = ล้มเหลว (ไฟล์อื่นไม่ถูกยกเลิก)", "samples/sample.docx, bad.pdf"),
 "WQA-DOC-03": ("Medium", "Functional", "Project ใหม่", ["แท็บ Paste Text → กดบันทึกโดยไม่กรอก", "กรอกชื่อ + ข้อความ BRS", "กด บันทึกและเริ่มวิเคราะห์"], "แจ้งช่องบังคับ · บันทึกแล้วไปหน้า Processing ของเอกสาร v1", "ข้อความ BRS สั้น"),
 "WQA-DOC-04": ("High", "Functional", "มี CAM_BRS_v1.txt ใน Project", ["Upload → เลือก 'Version ใหม่ของ: CAM_BRS_v1.txt'", "อัปโหลด CAM_BRS_v2.txt", "เปิด Version Compare"], "ได้ v2 · หน้า Compare เลือก v1 → v2 อัตโนมัติ และแสดง Section ที่ เพิ่ม/ลบ/เปลี่ยน", "samples/CAM_BRS_v2.txt"),
 "WQA-DOC-05": ("Low", "Functional", "DOC-01", ["เปิด Dashboard ของ Project"], "ตาราง Document Processing มีเอกสารที่อัปโหลด", "-"),
 # ---------------------------------------------------------------- REQ / CLR / DASH / TRC
 "WQA-REQ-01": ("Medium", "Functional", "CAM demo", ["เปิด Requirement Explorer"], "แสดง 9 รายการ", "-"),
 "WQA-REQ-02": ("Medium", "Functional", "CAM demo", ["พิมพ์ RULE4-003 ในช่องค้นหา"], "เหลือ 1 แถว REQ-CAM-RULE4-003", "RULE4-003"),
 "WQA-REQ-03": ("Medium", "Functional", "CAM demo", ["เลือก Status = CONFLICT"], "ทุกแถวที่เหลือเป็น CONFLICT", "-"),
 "WQA-REQ-04": ("High", "Functional", "CAM demo", ["คลิก REQ-CAM-RULE4-003"], "แผง AI Analysis บอก 'ไม่มี Expected Result' และ 'ไม่ระบุ Role' และมีแผง Source", "-"),
 "WQA-REQ-05": ("High", "Functional", "มี Requirement สถานะ WAITING_FOR_REVIEW", ["กรอง WAITING_FOR_REVIEW → เลือกแถวแรก", "กด Approve (ยืนยันถ้าถาม Source)"], "แจ้ง 'Approve … แล้ว' และสถานะเป็น APPROVED", "-"),
 "WQA-REQ-06": ("Low", "Functional", "CAM demo", ["เลือก REQ-CAM-RULE3-001 → Comment", "ลองกดยืนยันโดยไม่กรอก", "กรอกข้อความแล้วยืนยัน"], "ปุ่มยืนยันกดไม่ได้เมื่อว่าง · Comment แสดงในแผง Requirement", "ข้อความ Comment"),
 "WQA-REQ-07": ("High", "RBAC", "Login เป็น ba", ["เลือก REQ-CAM-RULE3-002"], "อ่านได้ แต่ไม่มีปุ่ม Approve / Edit", "-"),
 "WQA-CLR-01": ("High", "Functional", "Login เป็น ba", ["แท็บ Questions → กด ตอบ แถวแรก", "ลองบันทึกโดยว่าง", "กรอกคำตอบ → บันทึกคำตอบ"], "ปุ่มบันทึกกดไม่ได้เมื่อว่าง · แจ้ง 'บันทึกคำตอบแล้ว' · ตารางแสดงคำตอบ 'โดย ba'", "คำตอบ BA"),
 "WQA-CLR-02": ("High", "Functional", "มี Conflict สถานะ OPEN", ["แท็บ Conflicts → 'ไม่ขัดแย้ง — ใช้ทั้งสอง'", "ใส่เหตุผล 2 ตัวอักษร", "ใส่เหตุผลเต็ม → ยืนยัน"], "ยืนยันไม่ได้เมื่อเหตุผล < 3 ตัว · Resolve แล้วสถานะ RESOLVED พร้อมเหตุผลในประวัติ", "เหตุผลการ Resolve"),
 "WQA-CLR-03": ("Medium", "Functional", "CAM demo", ["แท็บ Assumptions"], "ทุก Assumption ติดป้าย 'AI ASSUMPTION - NOT FOUND IN BRS'", "-"),
 "WQA-DASH-01": ("Medium", "Functional", "CAM demo", ["เปิด Dashboard", "กดลิงก์ Workflow 'Requirement (AI Draft)'"], "KPI '9 Requirement' และลิงก์พาไปหน้า Requirement", "-"),
 "WQA-TRC-01": ("Medium", "Functional", "CAM demo", ["เปิด Traceability", "คลิกลิงก์ REQ-CAM-RULE3-001"], "เห็นสาย Document v1 → Section → Requirement และลิงก์ไป Requirement Explorer", "-"),
 # ---------------------------------------------------------------- TD / AUTO / RUN
 "WQA-TD-01": ("High", "RBAC", "Login เป็น ba", ["เปิด Test Scenarios", "เรียก API generate"], "ไม่มีปุ่ม Generate Scenarios · API ได้ 403", "-"),
 "WQA-TD-02": ("High", "Functional", "Requirement ที่รอ Review ถูก Approve", ["กด Generate Scenarios", "กด Generate ซ้ำ"], "ได้ TS-CAM-xxx · กดซ้ำไม่เพิ่ม Scenario ซ้ำ", "-"),
 "WQA-TD-03": ("High", "Functional", "TD-02", ["กด 'เลือกทั้งหมดที่ยังไม่มี Test Case'", "กด 'สร้าง Test Case จาก Scenario'"], "ไปหน้า Test Cases และมี TC-CAM-xxx", "-"),
 "WQA-TD-04": ("Medium", "Functional", "TD-03", ["กรอง Test Type = Negative", "เปิดแถวแรก"], "แถวเป็น Negative · หน้ารายละเอียดมีปุ่ม Approve", "-"),
 "WQA-TD-05": ("High", "Functional", "TD-03", ["ติ๊ก เลือกทั้งหมด → Approve (n) → ยืนยัน"], "ทุกแถวแสดง 🔒 Locked", "-"),
 "WQA-TD-06": ("Medium", "Functional", "มี Test Case", ["กด Export Excel"], "ดาวน์โหลดไฟล์ .xlsx", "-"),
 "WQA-AUTO-01": ("High", "Functional", "Test Case ถูก Approve", ["เปิด Automation → Pytest", "เลือกทั้งหมด → Generate"], "เห็น Code Editor และไฟล์ app/services/rule_service.py", "-"),
 "WQA-RUN-01": ("Critical", "Functional", "AUTO-01", ["กด Run", "เปิดแท็บ Logs"], "ไปหน้า Test Run สถานะ PASSED · ผลราย TC-CAM · Log มีคำว่า passed", "-"),
 "WQA-RUN-02": ("Medium", "Functional", "RUN-01", ["เปิด Test Runs", "เปิด Dashboard"], "รายการ Run แรกเป็น PASSED · Dashboard แสดงผล Run ล่าสุด", "-"),
 # ---------------------------------------------------------------- WEX
 "WQA-WEX-01": ("Medium", "Negative", ADMIN, ["ใส่ URL ftp://example.test/file → สำรวจหน้าเว็บ"], "แจ้ง 'URL ต้องขึ้นต้นด้วย http:// หรือ https://' และไม่สร้างผลสำรวจ", "ftp://example.test/file"),
 "WQA-WEX-02": ("Critical", "Functional", "Practice site ทำงาน", ["ใส่ URL หน้า Login ฝึก + Username/Password", "ปิดโหมดฝึก → สำรวจหน้าเว็บ"], "เห็นภาพก่อน/หลัง Login · ประวัติแสดง Login 'สำเร็จ' · แท็บ Test Cases มี TC-LOGIN-xxx", "demo / demo-pass-1"),
 "WQA-WEX-03": ("Critical", "Functional", "WEX-02", ["เปิดผลสำรวจ → แท็บ ③ pytest + รัน", "กด Run pytest"], "เห็นไฟล์ conftest.py · ผลการรันล่าสุด PASSED และ 'มี Login'", "-"),
 "WQA-WEX-04": ("Medium", "Functional", "WEX-02", ["กด ดาวน์โหลดโปรเจกต์ pytest (ZIP)"], "ได้ไฟล์ webtest_*.zip", "-"),
 "WQA-WEX-05": ("High", "Functional", "WEX-02", ["สำรวจหน้าเดิมอีกครั้ง"], "แสดง 'ก่อนรอบนี้สำรวจแล้ว 1 ครั้ง' (ไม่ออกแบบ Test Case ซ้ำ)", "-"),
 "WQA-WEX-06": ("High", "RBAC", "Login เป็น qa_manual", ["เปิด /web-explorer"], "แจ้ง 'ต้องมีสิทธิ์ Generate Automation' · ไม่มีฟอร์มสำรวจ · ไม่มีเมนู Web Explorer", "-"),
 "WQA-WEX-07": ("Medium", "Functional", "มีผลสำรวจ", ["เปิดผลสำรวจ → กด ลบ", "เปิด Web History"], "ผลสำรวจหายจากรายการ แต่ประวัติ Test Case ของหน้ายังอยู่", "-"),
 # ---------------------------------------------------------------- REC
 "WQA-REC-01": ("Critical", "Functional", ADMIN, ["Web Explorer → บันทึกการใช้งาน (Record)", "ใส่ URL + ชื่อ Test Case แรก → ▶ เริ่มบันทึก"], "หน้าต่าง browser เปิดหน้า URL · สถานะ 'กำลังบันทึก รอบที่ 1'", "shop.html"),
 "WQA-REC-02": ("High", "Negative", "REC-01 กำลังบันทึก", ["เริ่มบันทึกอีกรายการผ่าน API"], "ได้ 409 RECORDER_BUSY", "-"),
 "WQA-REC-03": ("Critical", "Functional", "REC-01", ["ในหน้าต่าง: คลิกเมนู WOMEN (CSS ตัวใหญ่ + ไอคอน) แล้ว Dress"], "ตาราง Script แสดง 'กดลิงก์ \"Women\"' และ 'กดลิงก์ \"Dress\" → ไปหน้า /register.html' · คำสั่งใช้ NAME(\"Women\")", "-"),
 "WQA-REC-04": ("High", "Functional", "REC-03", ["เพิ่มตรวจข้อความ 'สมัครสมาชิก'", "Add Test Case 'กรอกชื่อสมัครสมาชิก'", "ในหน้าต่าง: กด ลงทะเบียน + กรอกชื่อ"], "มีขั้น 'ตรวจว่าเห็นข้อความ' · Test Case 2 จาก 'กำลังรอขั้นตอนแรก' เป็น '2 ขั้นตอน'", "สมหญิง ทดสอบ"),
 "WQA-REC-05": ("High", "Functional", "REC-04", ["กด ⏸ หยุดบันทึก (จบรอบนี้)", "ในหน้าต่าง: กรอกอีเมล"], "แสดง 'หยุดบันทึกแล้ว (จบรอบที่ 1)' · ฟอร์มรอบใหม่เติม URL หน้าปัจจุบัน · สิ่งที่ทำระหว่างหยุดไม่ถูกบันทึก", "paused@example.test"),
 "WQA-REC-06": ("Critical", "Functional", "REC-05", ["ใส่ชื่อ + URL index.html → ▶ เริ่มรอบใหม่", "ในหน้าต่าง: กรอกชื่อผู้ใช้"], "สถานะ 'รอบที่ 2' · หน้าต่างเปิด index.html · ป้าย '⟳ Test Case 3' และขั้น 'เปิดหน้า … (เริ่ม Test Case ใหม่)'", "-"),
 "WQA-REC-07": ("High", "Functional", "REC-06", ["Add Test Case แล้วกดบันทึกทันที", "กด กลับไปบันทึกต่อ", "ในหน้าต่าง: กด เข้าสู่ระบบ"], "เตือนว่า Test Case ล่าสุดยังไม่มีขั้นตอน 'จะไม่ถูกสร้าง' · กลับไปบันทึกต่อได้ · Test Case 4 มีขั้นตอน", "-"),
 "WQA-REC-08": ("Critical", "Functional", "REC-07", ["กด ■ บันทึกเป็น Test Case และปิด browser"], "แจ้ง 'บันทึกแล้ว … · 4 Test Case' · แท็บ Test Cases มีทั้ง 4 สถานการณ์ · หน้า Record reset และจำ URL ล่าสุด", "-"),
 "WQA-REC-09": ("Medium", "Functional", "REC-08", ["เปิดผลบันทึก → ⑤ Script ทีละขั้น"], "มีคอลัมน์ 'อยู่ตรงไหน' (ส่วนของหน้าจอ) และคำสั่ง page.goto ของรอบใหม่", "-"),
 "WQA-REC-10": ("Critical", "Functional", "REC-08", ["④ Test Automation → ความเร็ว เร็ว → ▶ เล่นซ้ำ"], "PASSED · ผ่าน n/n · มีภาพประกอบขั้นที่ 1", "-"),
 "WQA-REC-11": ("High", "Negative", ADMIN, ["เริ่มบันทึกแล้วปิดหน้าต่างทันที", "กดบันทึก"], "ระหว่างยังไม่มีขั้นตอนปุ่มบันทึกกดไม่ได้ · หลังปิดหน้าต่างกดได้ · แจ้งไม่มีขั้นตอน และกลับหน้าเริ่มบันทึก (จำ URL)", "-"),
 "WQA-REC-12": ("Medium", "Negative", "ไม่มีการบันทึกค้าง", ["เริ่มบันทึกด้วย ftp://", "เริ่มบันทึกด้วยบัญชี ba"], "422 และ 403", "-"),
 "WQA-REC-13": ("Critical", "Functional", ADMIN, ["เริ่มบันทึก → กด ลงทะเบียน ในหน้าต่าง", "ปิดหน้าต่าง browser เอง", "กดบันทึก"], "ไม่มี error · ได้ 1 Test Case 1 ขั้นตอน (ขั้นตอนไม่หาย)", "DEF-WQA-02"),
 # ---------------------------------------------------------------- HIS / LIB
 "WQA-HIS-01": ("High", "Functional", "เคยสำรวจหน้า Login ฝึก", ["เมนู Web History → แท็บ รายหน้าเว็บ → คลิกหน้า"], "แสดงหน้า 127.0.0.1:8765/index.html, KPI 'Test Case สะสม' และตาราง Test Case", "-"),
 "WQA-HIS-02": ("Medium", "Functional", "HIS-01", ["กรองกลุ่ม Login", "ล้างกลุ่ม แล้วค้นหา WP-001"], "กรองแล้วจำนวนลดลง · ค้นหาเหลือ 1 แถว WP-001", "WP-001"),
 "WQA-HIS-03": ("Critical", "Functional", "HIS-01", ["คลิกแถว Test Case (ช่องขั้นตอน)"], "ไปหน้า /web-explorer/history/case?key=…&hid=… มี Test Case ID, Pre-condition, Steps, Expected, ที่มา และโค้ด def test_", "-"),
 "WQA-HIS-04": ("High", "Functional", "HIS-03", ["เปิด WP-001 → ถัดไป ›", "กด Back ของ browser", "← กลับไปรายการ Test Case"], "ก่อนหน้าปิดที่ข้อ 1 · ไป WP-002 (ข้อที่ 2) · Back กลับข้อที่ 1 · กลับหน้ารายการได้", "-"),
 "WQA-HIS-05": ("Low", "Functional", "HIS-03", ["กด คัดลอกเป็นข้อความ"], "Clipboard มี WP-001, 'ขั้นตอน:' และ 'ผลที่คาดหวัง:'", "-"),
 "WQA-HIS-06": ("Medium", "Negative", "-", ["เปิด …/case?hid=WP-999"], "แจ้ง 'ไม่พบ Test Case WP-999'", "WP-999"),
 "WQA-HIS-07": ("Medium", "Functional", "HIS-01", ["กด Export CSV (Excel)", "กด pytest รวมทุก TC (ZIP)"], "ได้ไฟล์ .csv และ .zip", "-"),
 "WQA-HIS-08": ("Medium", "RBAC", "Login เป็น ba", ["เปิดหน้ารายละเอียด WP-001"], "อ่านได้ (สิทธิ์ auto.view)", "-"),
 "WQA-LIB-01": ("High", "Functional", "มีประวัติ Test Case", ["เปิด Web History (แท็บคลังรวม)", "กดหมวด Login"], "ทุกแถวมี TL-ID ไม่ซ้ำ · กรองหมวดแล้วแสดงเฉพาะหมวดนั้น", "-"),
 "WQA-LIB-02": ("Medium", "Functional", "LIB-01", ["คลิก WP-ID ในคอลัมน์ 'พบในเว็บ'"], "เปิดหน้ารายละเอียด Test Case ของหน้านั้น", "-"),
 "WQA-LIB-03": ("Medium", "Functional", "LIB-01", ["กด ดาวน์โหลด Excel (.xlsx)"], "ได้ไฟล์ web_test_case_library.xlsx", "-"),
 # ---------------------------------------------------------------- ADM / AUD
 "WQA-ADM-01": ("High", "Functional", ADMIN, ["Settings → เพิ่มผู้ใช้ (Role QA Automation) → บันทึก", "ออกจากระบบแล้ว Login ด้วยผู้ใช้ใหม่"], "แจ้ง 'เพิ่มผู้ใช้แล้ว' และอยู่ในตาราง · Login ครั้งแรกถูกพาไปเปลี่ยนรหัสผ่าน", "Temp-Pass!12345"),
 "WQA-ADM-02": ("Medium", "Negative", ADMIN, ["เพิ่มผู้ใช้ด้วยรหัสผ่าน 'short'"], "ไม่สร้างผู้ใช้ (dialog ยังเปิด)", "short"),
 "WQA-ADM-03": ("Medium", "Functional", "ADM-01", ["เปลี่ยน Role ของผู้ใช้เป็น Business Analyst"], "แจ้ง 'เปลี่ยน Role แล้ว' และ API คืน roles = ['BA']", "-"),
 "WQA-ADM-04": ("High", "Security", "ADM-01", ["กด ปิด ที่แถวผู้ใช้", "ผู้ใช้นั้นลอง Login"], "แจ้ง 'ปิดบัญชีแล้ว' · Login ไม่ได้", "-"),
 "WQA-ADM-05": ("Critical", "Security", ADMIN, ["เปิดแท็บ AI Provider / GitHub / Network Sharing / Session", "GET /api/settings"], "ไม่แสดงค่า Secret ใด ๆ (แสดงเพียงสถานะ)", "-"),
 "WQA-ADM-06": ("Low", "Functional", ADMIN, ["แท็บ Test Runner → Timeout = 150", "กด บันทึก (1) → reload"], "แจ้ง 'บันทึก Settings แล้ว' และค่าคงอยู่หลัง reload", "150"),
 "WQA-AUD-01": ("High", "Security", "มี Login ผิด 1 ครั้ง", ["Audit Log → Action = LOGIN_FAILED", "User = admin"], "แสดงรายการ LOGIN_FAILED ของ admin", "-"),
 "WQA-AUD-02": ("Critical", "Security", ADMIN, ["Export CSV", "ค้นรหัสผ่านในไฟล์"], "ได้ audit_log.csv และไม่มีรหัสผ่าน (ถูก/ผิด/ชั่วคราว) ในไฟล์", "-"),
 "WQA-AUD-03": ("Medium", "Functional", "-", ["GET /api/audit-logs"], "มี LOGIN / PASSWORD_CHANGED และ correlation_id 8 หลัก", "-"),
 "WQA-AUD-04": ("High", "RBAC", "Login เป็น qa_auto", ["เปิด /audit-log และ /settings"], "แสดง 'เฉพาะ Admin' ไม่มีข้อมูลหรือปุ่มจัดการ", "-"),
 # ---------------------------------------------------------------- API / SEC
 "WQA-API-01": ("High", "API", "-", ["GET /api/health"], "200 status ok (ไม่ต้อง Login)", "-"),
 "WQA-API-02": ("Critical", "Security", "-", ["เรียก 9 Endpoint ภายในแบบไม่มี Token และ Token ปลอม"], "ทุกครั้งได้ 401", "-"),
 "WQA-API-03": ("Medium", "API", "-", ["GET /api/projects โดยไม่ Login"], "Error มี code, user_message, timestamp, retryable, suggested_action, correlation_id + Header X-Correlation-Id และไม่มี technical", "-"),
 "WQA-API-04": ("Medium", "API", "-", ["ส่ง body ผิดรูปแบบไป login / projects / web-explorer"], "ได้ 422 (ไม่ใช่ 500)", "javascript:alert(1)"),
 "WQA-API-05": ("Medium", "API", "-", ["GET /api/auth/me ด้วย Token"], "มี Header X-Refreshed-Token", "-"),
 "WQA-API-06": ("High", "Security", "-", ["GET /api/users"], "ไม่มี password_hash / bcrypt hash / token", "-"),
 "WQA-SEC-01": ("High", "Security", "-", ["เรียก Web History / Screenshot ด้วย ..%2F"], "ได้ 404/422 ไม่หลุดไฟล์ระบบ", "..%2F..%2Fsecrets"),
 "WQA-SEC-02": ("High", "Security", "-", ["GET /login ของหน้าเว็บ"], "X-Frame-Options DENY, nosniff, no-referrer, CSP frame-ancestors 'none', ไม่มี X-Powered-By", "-"),
 "WQA-SEC-03": ("Medium", "Security", "-", ["Login แล้วตรวจที่เก็บ Token"], "Token อยู่ใน sessionStorage เท่านั้น (ไม่อยู่ใน Cookie / localStorage)", "-"),
 "WQA-SEC-04": ("Medium", "Security", "-", ["GET /web-explorer/does-not-exist"], "404 ไม่มี Traceback / path ของ Server", "-"),
}

EXTRA = [  # not in the Playwright suite
 ("WQA-PERF-01", "PERF", "Load: 50 ผู้ใช้พร้อมกัน 20–30 วินาที (Projects → Dashboard → Requirements → Web History → Library)", "Critical", "Performance",
  "Backend เปิดอยู่ · บัญชีทดสอบ", ["python perf/webqa_perf.py --mode load --users 50 --duration 30 --password …"], "p95 < 2,000 ms และ error < 2% · Server ยังตอบได้หลังทดสอบ", "-", "perf/webqa_perf.py --mode load", "ผ่าน: 114 req/s · p95 1,027 ms · error 0% (หลังแก้ DEF-WQA-03/04)", "DEF-WQA-03, DEF-WQA-04"),
 ("WQA-PERF-02", "PERF", "Stress: เพิ่มผู้ใช้ 10 → 25 → 50 → 100 → 200 → 400 หา Breaking point", "High", "Performance",
  "Backend เปิดอยู่", ["python perf/webqa_perf.py --mode stress --levels 10,25,50,100,200,400 --step 15 --password …"], "รายงานระดับที่เกิน SLA ครั้งแรก (Breaking point) และไม่มี error 5xx", "-", "perf/webqa_perf.py --mode stress", "Breaking point ≈ 100 ผู้ใช้ (p95 2,735 ms) · error 0%", ""),
 ("WQA-PERF-03", "PERF", "Spike: 5 → 300 → 5 ผู้ใช้ ระบบต้องฟื้นตัว", "High", "Performance",
  "Backend เปิดอยู่", ["python perf/webqa_perf.py --mode spike --users 300 --password …"], "หลัง spike ช่วงสุดท้ายกลับมาผ่าน SLA (ฟื้นตัว)", "-", "perf/webqa_perf.py --mode spike", "ฟื้นตัว: p95 73 ms · ช่วง spike p95 9.2 s error 0.62%", ""),
 ("WQA-PERF-04", "PERF", "Rate limit Login 5 ครั้ง/นาที/IP (กันเดารหัสผ่าน)", "Critical", "Security",
  "Backend ใช้ค่า .env ปกติ", ["python perf/webqa_perf.py --mode ratelimit --password …"], "Login ผิดครั้งที่ 5+ ได้ 429", "-", "perf/webqa_perf.py --mode ratelimit", "ผ่าน: 401×4 แล้ว 429", ""),
 ("WQA-PERF-05", "PERF", "Rate limit API 600 ครั้ง/นาที/IP", "Medium", "Performance",
  "Backend ใช้ค่า .env ปกติ", ["python perf/webqa_perf.py --mode ratelimit --password …"], "เกิน ~600 ครั้ง/นาที ได้ 429 (ไม่ใช่ server ล่ม)", "-", "perf/webqa_perf.py --mode ratelimit", "ผ่าน: 429 ครั้งแรกที่ request #592", ""),
 ("WQA-PERF-06", "PERF", "คำขอพร้อมกันเกินจำนวน connection ของฐานข้อมูล → Server ต้องไม่ค้าง", "Critical", "Performance",
  "Backend เปิดอยู่", ["ยิง 50 ผู้ใช้ 20 วินาที", "เรียก /api/health หลังจบ"], "ตอบ /api/health ภายใน 1 วินาทีหลังโหลดจบ", "-", "perf/webqa_perf.py --mode load", "ผ่าน (ก่อนแก้: ค้างถาวร ต้อง restart)", "DEF-WQA-03"),
 ("WQA-PERF-07", "PERF", "เปิดคลัง Test Case พร้อมกัน 12 คน × 15 ครั้ง → ไฟล์ index ไม่เสีย TL-ID ไม่ซ้ำ", "High", "Performance",
  "-", ["pytest backend/tests/test_web_explorer.py -k concurrent"], "ไม่มี error · TL-ID ไม่ซ้ำ", "-", "backend pytest :: test_library_and_history_files_survive_concurrent_requests", "ผ่าน", "DEF-WQA-04"),
 ("WQA-REC-14", "REC", "ปิดหน้าต่าง Recorder ระหว่างที่ระบบกำลังรอ → ขั้นตอนไม่หาย (ระดับ Service)", "Critical", "Functional",
  "-", ["pytest backend/tests/test_web_explorer.py -k closing_the_recorder"], "สถานะ stopped และมีขั้นตอนครบ", "-", "backend pytest :: test_closing_the_recorder_window_keeps_the_steps", "ผ่าน", "DEF-WQA-02"),
 ("WQA-MAN-01", "MAN", "Recorder บน Windows (หน้าต่างจริง) — เว็บที่ขอ passkey ไม่เด้งหน้าต่าง Windows Security / บัญชี Microsoft", "High", "Functional",
  "RUN-DEV.bat บน Windows", ["Record เว็บที่มีปุ่ม Sign in with passkey", "สังเกตหน้าต่างของ Windows"], "ไม่มีหน้าต่าง Windows Security เด้งขึ้น", "-", "Manual", "ยังไม่ทดสอบบน Windows", ""),
 ("WQA-MAN-02", "MAN", "หน้าเว็บบนจอแคบ (≤ 1100 px) / ซูม 150% อ่านได้ ไม่มีปุ่มซ้อนกัน", "Low", "Usability",
  "-", ["ย่อหน้าต่าง browser เหลือ 1000 px", "เปิด Web Explorer / History / Detail"], "ตารางเลื่อนแนวนอนได้ ปุ่มกดได้ครบ", "-", "Manual", "ยังไม่ทดสอบ", ""),
 ("WQA-MAN-03", "MAN", "Session หมดอายุเมื่อไม่ใช้งานเกิน SESSION_MINUTES (30 นาที)", "Medium", "Security",
  ADMIN, ["ไม่ใช้งาน 31 นาที", "คลิกเมนูใดก็ได้"], "ถูกพาไปหน้า Login พร้อมเหตุผล", "SESSION_MINUTES=1 เพื่อทดสอบเร็ว", "Manual", "ยังไม่ทดสอบ", ""),
 ("WQA-MAN-04", "MAN", "Exploratory: ใช้ Recorder กับเว็บจริงที่มี iframe / แท็บใหม่ / popup โฆษณา", "Medium", "Exploratory",
  "เว็บทดสอบสาธารณะ เช่น automationexercise.com", ["Record 10 นาที ตาม Charter: เมนู, Add to cart, ลิงก์เปิดแท็บใหม่", "เล่นซ้ำ + Run pytest"], "บันทึกข้อสังเกต/Bug ใน Session sheet", "-", "Manual", "ยังไม่ทดสอบ", ""),
]

DEFECTS = [
 ("DEF-WQA-01", "Medium", "Open", "WQA-AUTH-09", "เปิดลิงก์ภายในตอนยังไม่ Login แล้ว Login → ไป /projects แทนหน้าเดิม",
  "frontend/lib/auth.tsx: เมื่อ /auth/me ได้ 401 จะ router.replace('/login?reason=…') โดยไม่ใส่ next=<path> (AppShell ใส่ next แต่ 401 handler ทำงานก่อน)",
  "ใส่ next=pathname ใน 401 handler เหมือน logout()"),
 ("DEF-WQA-02", "Critical", "Fixed", "WQA-REC-13, WQA-REC-14", "ปิดหน้าต่าง Recorder เอง → RECORDER_FAILED 'Target page … has been closed' และขั้นตอนที่บันทึกหายทั้งหมด",
  "web_recorder._run: page.wait_for_timeout() โยน error เมื่อหน้าต่างถูกปิดระหว่างรอ → สถานะ error",
  "จับ error แล้วตรวจว่ายังมีหน้าต่างเหลือไหม ถ้าไม่มีจบแบบ stopped (เก็บขั้นตอนไว้)"),
 ("DEF-WQA-03", "Critical", "Fixed", "WQA-PERF-01, WQA-PERF-06", "ผู้ใช้ ~50 คำขอพร้อมกัน → Backend ค้างถาวร (/api/health ก็ไม่ตอบ ต้อง restart)",
  "SQLAlchemy QueuePool 5+10 connection < worker threads 40: ทุก thread รอ connection แต่การคืน connection (get_db cleanup) ต้องใช้ thread → deadlock",
  "SQLite ใช้ NullPool · DB อื่น pool_size 10 + max_overflow 50"),
 ("DEF-WQA-04", "High", "Fixed", "WQA-PERF-01, WQA-PERF-07", "เปิดคลัง Test Case พร้อมกันหลายคน → HTTP 500 'Expecting value' (3.6% ของคำขอ)",
  "GET /web-library เขียน library_index.json ใหม่ทุกครั้งแบบไม่ atomic ขณะที่คำขออื่นกำลังอ่าน (ไฟล์ว่างชั่วขณะ)",
  "เขียนไฟล์แบบ atomic (temp + rename, retry บน Windows) · ล็อกตอนสร้าง index · เขียนเฉพาะเมื่อมี TL-ID ใหม่"),
 ("DEF-WQA-05", "Low", "Open", "WQA-REC-12", "เริ่ม Recorder ด้วย URL ผิดระหว่างที่มีการบันทึกค้าง → ได้ 409 RECORDER_BUSY แทน 422",
  "wr.start() ตรวจ 'มีการบันทึกอยู่' ก่อนตรวจ URL", "ตรวจ URL ก่อน (check_url) แล้วค่อยตรวจ busy"),
 ("DEF-WQA-06", "Medium", "Open (ข้อเสนอแนะ)", "WQA-PERF-02", "GET /web-history เรียก backfill() ไล่อ่าน result.json ทุกไฟล์ทุกครั้ง → ช้าลงตามจำนวนผลสำรวจ",
  "backfill ควรทำครั้งเดียวตอน start หรือเมื่อมีไฟล์ใหม่", "ย้าย backfill ไปตอน startup / จำ mtime ล่าสุด"),
 ("DEF-WQA-07", "Low", "Open (ข้อสังเกต)", "WQA-PERF-05", "Rate limit 600 ครั้ง/นาที คิดต่อ IP — ถ้าแชร์ผ่าน LAN/NAT หลายคนใช้ IP เดียวกัน (หน้า Record poll ทุก 1 วินาที) อาจโดน 429",
  "ค่า API_RATE_PER_MINUTE ต่อ IP", "คิดต่อผู้ใช้ (token) แทน หรือเพิ่มค่าเมื่อเปิด Network Sharing"),
]
