"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-10-01 22:06:13.583102
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_entity_id'), 'approvals', ['entity_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('id_sequences',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('module_codes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('automation_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('test_case_ids', sa.JSON(), nullable=False),
    sa.Column('tc_codes', sa.JSON(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('scan_problems', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_artifacts_project_id'), 'automation_artifacts', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_module', sa.String(length=32), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('github_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('repo', sa.String(length=100), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('encoding', sa.String(length=40), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('ai_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('github_action_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('repository', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('base_branch', sa.String(length=200), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('scan_problems', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_action_requests_project_id'), 'github_action_requests', ['project_id'], unique=False)
    op.create_table('impact_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('section_diff', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('retest', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_analyses_project_id'), 'impact_analyses', ['project_id'], unique=False)
    op.create_table('jmeter_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('target_url', sa.String(length=300), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('playwright_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('browser', sa.String(length=20), nullable=False),
    sa.Column('page_name', sa.String(length=80), nullable=False),
    sa.Column('locators', sa.JSON(), nullable=False),
    sa.Column('manual_checkpoints', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('postman_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('pytest_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('test_files', sa.JSON(), nullable=False),
    sa.Column('markers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('python_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('rule_functions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('sql_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('dialect', sa.String(length=20), nullable=False),
    sa.Column('query_types', sa.JSON(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['automation_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_project_id'), 'test_runs', ['project_id'], unique=False)
    op.create_table('document_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('alt', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('near_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_images_version_id'), 'document_images', ['version_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('parent_title', sa.String(length=400), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('row_offset', sa.Integer(), nullable=False),
    sa.Column('overlap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sections_version_id'), 'document_sections', ['version_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('ai_mode', sa.String(length=16), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_version_id'), 'processing_jobs', ['version_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('req_id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('doc_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('submodule', sa.String(length=400), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('business_rule', sa.Text(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('process', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('threshold', sa.String(length=80), nullable=False),
    sa.Column('threshold_op', sa.String(length=10), nullable=False),
    sa.Column('threshold_value', sa.String(length=40), nullable=False),
    sa.Column('threshold_raw', sa.String(length=200), nullable=False),
    sa.Column('threshold_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('date_range', sa.String(length=200), nullable=False),
    sa.Column('inclusion', sa.Text(), nullable=False),
    sa.Column('exclusion', sa.Text(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('ai_meta', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('completeness_reasons', sa.JSON(), nullable=False),
    sa.Column('clarity_score', sa.Integer(), nullable=False),
    sa.Column('clarity_reasons', sa.JSON(), nullable=False),
    sa.Column('source_unverified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conflict_status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_of', sa.String(length=80), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('supersedes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_req_project_status', 'requirements', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_req_id'), 'requirements', ['req_id'], unique=True)
    op.create_table('test_run_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_artifacts_run_id'), 'test_run_artifacts', ['run_id'], unique=False)
    op.create_table('test_run_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=True),
    sa.Column('tc_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_results_run_id'), 'test_run_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_run_results_test_case_id'), 'test_run_results', ['test_case_id'], unique=False)
    op.create_table('processing_job_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('req_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_job_sections_job_id'), 'processing_job_sections', ['job_id'], unique=False)
    op.create_table('requirement_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('req_a_id', sa.String(length=36), nullable=False),
    sa.Column('req_b_id', sa.String(length=36), nullable=False),
    sa.Column('similarity', sa.Integer(), nullable=False),
    sa.Column('diffs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['req_a_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['req_b_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_conflicts_project_id'), 'requirement_conflicts', ['project_id'], unique=False)
    op.create_table('requirement_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('answered_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_questions_requirement_id'), 'requirement_questions', ['requirement_id'], unique=False)
    op.create_table('requirement_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('page', sa.String(length=20), nullable=False),
    sa.Column('page_end', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=400), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('table_ref', sa.String(length=400), nullable=False),
    sa.Column('screenshot_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_sources_requirement_id'), 'requirement_sources', ['requirement_id'], unique=False)
    op.create_table('requirement_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_versions_requirement_id'), 'requirement_versions', ['requirement_id'], unique=False)
    op.create_table('test_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('pr_reasons', sa.JSON(), nullable=False),
    sa.Column('source_page', sa.String(length=20), nullable=False),
    sa.Column('source_section', sa.String(length=400), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scenarios_project_id'), 'test_scenarios', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_scenarios_requirement_id'), 'test_scenarios', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_test_scenarios_ts_id'), 'test_scenarios', ['ts_id'], unique=True)
    op.create_table('requirement_assumptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['requirement_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_assumptions_requirement_id'), 'requirement_assumptions', ['requirement_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tc_id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('req_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_explanation', sa.Text(), nullable=False),
    sa.Column('given', sa.Text(), nullable=False),
    sa.Column('when', sa.Text(), nullable=False),
    sa.Column('then', sa.Text(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('overall_expected', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('risk', sa.String(length=10), nullable=False),
    sa.Column('pr_reasons', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('automation_candidate', sa.String(length=10), nullable=False),
    sa.Column('automation_tool', sa.String(length=40), nullable=False),
    sa.Column('assumption', sa.Text(), nullable=False),
    sa.Column('clarification_ref', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=20), nullable=False),
    sa.Column('source_section', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_cases_requirement_id'), 'test_cases', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_test_cases_scenario_id'), 'test_cases', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_test_cases_tc_id'), 'test_cases', ['tc_id'], unique=True)
    op.create_table('test_scenario_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scenario_versions_scenario_id'), 'test_scenario_versions', ['scenario_id'], unique=False)
    op.create_table('test_case_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_versions_test_case_id'), 'test_case_versions', ['test_case_id'], unique=False)
    op.create_table('test_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('raw', sa.String(length=200), nullable=True),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_test_case_id'), 'test_data', ['test_case_id'], unique=False)
    op.create_table('test_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('test_data', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_steps_test_case_id'), 'test_steps', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_steps_test_case_id'), table_name='test_steps')
    op.drop_table('test_steps')
    op.drop_index(op.f('ix_test_data_test_case_id'), table_name='test_data')
    op.drop_table('test_data')
    op.drop_index(op.f('ix_test_case_versions_test_case_id'), table_name='test_case_versions')
    op.drop_table('test_case_versions')
    op.drop_index(op.f('ix_test_scenario_versions_scenario_id'), table_name='test_scenario_versions')
    op.drop_table('test_scenario_versions')
    op.drop_index(op.f('ix_test_cases_tc_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_scenario_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_requirement_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_requirement_assumptions_requirement_id'), table_name='requirement_assumptions')
    op.drop_table('requirement_assumptions')
    op.drop_index(op.f('ix_test_scenarios_ts_id'), table_name='test_scenarios')
    op.drop_index(op.f('ix_test_scenarios_requirement_id'), table_name='test_scenarios')
    op.drop_index(op.f('ix_test_scenarios_project_id'), table_name='test_scenarios')
    op.drop_table('test_scenarios')
    op.drop_index(op.f('ix_requirement_versions_requirement_id'), table_name='requirement_versions')
    op.drop_table('requirement_versions')
    op.drop_index(op.f('ix_requirement_sources_requirement_id'), table_name='requirement_sources')
    op.drop_table('requirement_sources')
    op.drop_index(op.f('ix_requirement_questions_requirement_id'), table_name='requirement_questions')
    op.drop_table('requirement_questions')
    op.drop_index(op.f('ix_requirement_conflicts_project_id'), table_name='requirement_conflicts')
    op.drop_table('requirement_conflicts')
    op.drop_index(op.f('ix_processing_job_sections_job_id'), table_name='processing_job_sections')
    op.drop_table('processing_job_sections')
    op.drop_index(op.f('ix_test_run_results_test_case_id'), table_name='test_run_results')
    op.drop_index(op.f('ix_test_run_results_run_id'), table_name='test_run_results')
    op.drop_table('test_run_results')
    op.drop_index(op.f('ix_test_run_artifacts_run_id'), table_name='test_run_artifacts')
    op.drop_table('test_run_artifacts')
    op.drop_index(op.f('ix_requirements_req_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index('ix_req_project_status', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_processing_jobs_version_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_document_sections_version_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_document_images_version_id'), table_name='document_images')
    op.drop_table('document_images')
    op.drop_index(op.f('ix_test_runs_project_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_table('sql_artifacts')
    op.drop_table('python_artifacts')
    op.drop_table('pytest_artifacts')
    op.drop_table('postman_artifacts')
    op.drop_table('playwright_artifacts')
    op.drop_table('jmeter_artifacts')
    op.drop_index(op.f('ix_impact_analyses_project_id'), table_name='impact_analyses')
    op.drop_table('impact_analyses')
    op.drop_index(op.f('ix_github_action_requests_project_id'), table_name='github_action_requests')
    op.drop_table('github_action_requests')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('user_roles')
    op.drop_table('project_members')
    op.drop_table('github_integrations')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_automation_artifacts_project_id'), table_name='automation_artifacts')
    op.drop_table('automation_artifacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('id_sequences')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvals_entity_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
