from __future__ import annotations

from ..engine.text import NF
from ..testdesign import is_length
from .common import GenTC, one_line, py_str, slug, tip


def rule_entries(tcs: list[GenTC]) -> list[dict]:
    rules, seen = [], set()
    for tc in tcs:
        r, f = tc.req, tc.f
        if r and f["threshold_value"] != NF and f["threshold_op"] != NF and r["id"] not in seen:
            seen.add(r["id"])
            rules.append({"r": r, "f": f, "fn": "meets_" + slug(r["req_id"]), "const": slug(r["req_id"]).upper() + "_THRESHOLD",
                          "length": is_length(f["unit"]), "tcs": [t.tc_id for t in tcs if t.req and t.req["id"] == r["id"]]})
    return rules


def _rule_block(x: dict) -> str:
    r, f = x["r"], x["f"]
    op = "==" if f["threshold_op"] == "=" else f["threshold_op"]
    head = (f"# {r['req_id']} | Source: {r['source'].get('doc_name')} หน้า {r['source'].get('page')} / {r['source'].get('section')}\n"
            f"# BRS: {one_line(r['original_text'], 150)}\n")
    if x["length"]:
        return head + (f"{x['const']} = {int(float(f['threshold_value']))}  # unit: {f['unit']} (length)\n\n\n"
                       f"def {x['fn']}(value: str) -> bool:\n"
                       f"    \"\"\"Return True when len(value) satisfies '{f['threshold_op']} {f['threshold_value']}' ({r['req_id']}).\"\"\"\n"
                       f"    return len(value) {op} {x['const']}\n")
    return head + (f"{x['const']} = Decimal({py_str(f['threshold_value'])})  # unit: {f['unit']}\n\n\n"
                   f"def {x['fn']}(value: Decimal) -> bool:\n"
                   f"    \"\"\"Return True when value satisfies '{f['threshold_op']} {f['threshold_value']}' ({r['req_id']}).\"\"\"\n"
                   f"    return value {op} {x['const']}\n")


def gen_python_layer(tcs: list[GenTC], project: dict) -> dict:
    files: dict[str, str] = {}
    tips: dict[str, list] = {}
    rules = rule_entries(tcs)
    all_tc = ", ".join(t.tc_id for t in tcs)
    rule_tc = ", ".join(c for x in rules for c in x["tcs"]) or "-"
    files["app/__init__.py"] = ""
    files["app/services/__init__.py"] = ""
    body = "\n\n".join(_rule_block(x) for x in rules) or "# ไม่มี Requirement ที่มี Threshold เชิงตัวเลขใน Test Case ที่เลือก\n"
    files["app/services/rule_service.py"] = (f'"""Business rules extracted from BRS ({project["code"]}).\n'
                                             "Each constant links back to its Requirement ID and source page.\n"
                                             'Generated by BRS to QA Automation Platform — review before running.\n"""\n'
                                             f"from decimal import Decimal\n\n{body}\n")
    files["app/validators/__init__.py"] = ""
    files["app/validators/input_validator.py"] = '''from decimal import Decimal, InvalidOperation


class ValidationError(ValueError):
    """Raised when a required value is empty (Validation Error)."""


class InvalidDataTypeError(ValueError):
    """Raised when a value is not numeric (Invalid Data Type)."""


def parse_amount(raw) -> Decimal:
    """Convert raw input to Decimal. Empty -> ValidationError, non-numeric -> InvalidDataTypeError."""
    if raw is None or str(raw).strip() == "":
        raise ValidationError("Validation Error")
    try:
        return Decimal(str(raw).replace(",", ""))
    except InvalidOperation as exc:
        raise InvalidDataTypeError("Invalid Data Type") from exc


def parse_text(raw) -> str:
    """Text fields: None -> ValidationError; empty string is allowed (length rules decide)."""
    if raw is None:
        raise ValidationError("Validation Error")
    return str(raw)
'''
    files["app/utilities/__init__.py"] = ""
    files["app/utilities/date_helper.py"] = '''from datetime import date, datetime, timedelta
from zoneinfo import ZoneInfo

# AI ASSUMPTION - NOT FOUND IN BRS: timezone = Asia/Bangkok unless BA confirms otherwise
TZ = ZoneInfo("Asia/Bangkok")


def today() -> date:
    return datetime.now(TZ).date()


def days_back_range(days: int, end: date | None = None, inclusive: bool = True) -> tuple[date, date]:
    """Return (start, end) for a look-back window of 'days' calendar days."""
    end = end or today()
    start = end - timedelta(days=days - 1 if inclusive else days)
    return start, end


def in_range(d: date, start: date, end: date) -> bool:
    return start <= d <= end
'''
    files["app/utilities/file_helper.py"] = '''from pathlib import Path

REPORT_DIR = Path(__file__).resolve().parents[2] / "reports"


def ensure_report_dir() -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    return REPORT_DIR
'''
    files["app/utilities/api_helper.py"] = '''import os

import requests

# NEEDS_CONFIGURATION: set BASE_URL and AUTH_TYPE in .env (never commit .env)
BASE_URL = os.getenv("BASE_URL", "")
TIMEOUT = float(os.getenv("API_TIMEOUT", "30"))


def build_headers() -> dict:
    headers = {"Content-Type": "application/json"}
    token = os.getenv("API_TOKEN")
    if os.getenv("AUTH_TYPE", "none") == "bearer" and token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def get(path: str, **params):
    if not BASE_URL:
        raise RuntimeError("NEEDS_CONFIGURATION: BASE_URL is empty")
    return requests.get(f"{BASE_URL}{path}", headers=build_headers(), params=params, timeout=TIMEOUT)
'''
    files["app/repositories/__init__.py"] = ""
    files["app/repositories/transaction_repository.py"] = '''"""Repository pattern: all DB access goes through here (read-only by default).
NEEDS_CONFIGURATION: table/column names are placeholders until confirmed by BA/DBA.
"""
TRANSACTION_TABLE = "{{table_transaction}}"  # AI ASSUMPTION - NOT FOUND IN BRS


def select_by_customer_sql() -> str:
    return f"SELECT * FROM {TRANSACTION_TABLE} WHERE customer_id = %s AND txn_date BETWEEN %s AND %s"
'''
    files["app/models/__init__.py"] = ""
    files["test_data/__init__.py"] = ""
    files["test_data/factory.py"] = '''"""Synthetic test data factory — never use real customer data."""
from dataclasses import dataclass, field
from decimal import Decimal
from itertools import count

_seq = count(1)


@dataclass
class Customer:
    customer_id: str = field(default_factory=lambda: f"CUST-TEST-{next(_seq):04d}")
    name: str = "Synthetic Customer"


@dataclass
class Transaction:
    customer: Customer
    amount: Decimal
    product: str = "GENERAL"


def make_transaction(amount, product: str = "GENERAL") -> Transaction:
    return Transaction(customer=Customer(), amount=Decimal(str(amount)), product=product)
'''
    files["config/__init__.py"] = ""
    files["config/settings.py"] = '''import os

from dotenv import load_dotenv

load_dotenv()
ENV = os.getenv("TEST_ENV", "sit")
BASE_URL = os.getenv("BASE_URL", "")
'''
    tips["app/services/rule_service.py"] = [
        tip('Decimal("...")', "เก็บค่า Threshold จาก BRS", "ค่าตัวเลขจาก BRS", "ค่าคงที่ชนิด Decimal",
            "ใช้ Decimal แทน float เพราะตัวเลขจำนวนเงินต้องแม่นยำ float อาจทำให้ทศนิยมคลาดเคลื่อน เช่น 0.1+0.2",
            "ค่าคงที่แต่ละตัวมี Comment บอก Requirement ID และหน้าที่มา ถ้า BRS เปลี่ยนค่าแก้ที่จุดเดียว", rule_tc,
            "ห้ามแก้ค่าให้ต่างจาก BRS โดยไม่มี Clarification", "ตรวจว่าค่าและเครื่องหมายตรงกับ Requirement ที่ Approved"),
        tip("def meets_...(value)", "ตัดสินว่าค่าเข้าเงื่อนไข Business Rule หรือไม่", "value: Decimal (หรือ str สำหรับความยาว)", "True/False",
            "แยก Business Logic ออกจาก Test Function ทำให้ Test สั้นและนำ Logic ไปใช้ซ้ำได้ (Service Pattern)",
            "ฟังก์ชันเปรียบเทียบค่ากับ Threshold ด้วยเครื่องหมายที่ BRS ระบุ — กฎความยาวใช้ len()", rule_tc,
            "เครื่องหมาย > กับ >= ให้ผลต่างกันที่ค่าขอบพอดี", "ยืนยันเครื่องหมายกับ BA หากยังมี Clarification ค้าง"),
    ]
    tips["app/validators/input_validator.py"] = [tip("parse_amount(raw)", "แปลงค่าที่รับเข้ามาเป็นจำนวนเงิน", "ข้อความหรือตัวเลข", "Decimal หรือ Error",
                                                     "รวมการตรวจค่าว่างและชนิดข้อมูลไว้ที่เดียว (Validation Helper)",
                                                     "ค่าว่างจะเกิด ValidationError ค่าที่ไม่ใช่ตัวเลขจะเกิด InvalidDataTypeError", all_tc,
                                                     "ชื่อ Error ต้องตรงกับ Expected Result ใน Test Case", "ถ้า BRS ระบุ Error Message ให้แก้ข้อความให้ตรง")]
    tips["app/utilities/date_helper.py"] = [tip('ZoneInfo("Asia/Bangkok")', "กำหนด Timezone ของวันที่", "-", "วันที่ตามเวลาประเทศไทย",
                                                "ถ้าไม่ระบุ Timezone ผลการนับวันอาจคลาดเมื่อ Run บน Server ต่างประเทศหรือ GitHub Actions",
                                                "days_back_range คืนวันเริ่มและวันสิ้นสุดของช่วงย้อนหลัง", "-", "เป็น AI ASSUMPTION จนกว่า BA ยืนยัน",
                                                "ตรวจว่า Calendar Day/Business Day ตรงกับคำตอบ BA")]
    tips["test_data/factory.py"] = [tip("make_transaction()", "สร้างข้อมูลทดสอบแบบ Synthetic", "amount, product", "Transaction",
                                        "Test Data Factory ทำให้ Test ไม่ใช้ข้อมูลลูกค้าจริงและสร้างข้อมูลใหม่ได้ทุกครั้ง",
                                        "Customer ID ขึ้นต้นด้วย CUST-TEST- เพื่อแยกจากข้อมูลจริง", all_tc, "ห้ามแทนด้วย Customer ID จริง", "-")]
    tips["app/utilities/api_helper.py"] = [tip("BASE_URL = os.getenv(...)", "อ่าน URL ของระบบที่จะทดสอบจาก Environment", ".env", "URL",
                                               "ห้าม Hardcode URL/Token ใน Code เพื่อไม่ให้ Secret หลุดเข้า Git",
                                               "build_headers ใส่ Token เฉพาะเมื่อกำหนด AUTH_TYPE=bearer", "-",
                                               "Authentication ยังไม่ทราบ (NEEDS_CONFIGURATION)", "กำหนด BASE_URL, AUTH_TYPE ใน .env")]
    tips["app/repositories/transaction_repository.py"] = [tip("TRANSACTION_TABLE", "รวม SQL ไว้ใน Repository", "-", "SQL (Read-only)",
                                                              "Repository Pattern แยกการเข้าถึง Database ออกจาก Test", "ใช้ Parameter %s ป้องกัน SQL Injection",
                                                              all_tc, "ชื่อตารางเป็น Placeholder", "ยืนยันชื่อตารางกับ DBA")]
    return {"files": files, "tips": tips}
